# Generated by Django 5.1.3 on 2025-08-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='context',
            new_name='content',
        ),
    ]
